### ISSUE TITLE
haxball new update comes out!

### ISSUE THREAD

**Issue by gamingmastar** [vkurenkov/haxball-chameleon#3]
chameleon not working anymore, can't join servers!

**Comment by vkurenkov** [comment]
Hey,

We're already on it, it will take some time (up to 3-4 weeks) as any new update requires manual investigation, and we have quite busy working schedules right now.

**Comment by vkurenkov** [comment]
@gamingmastar sorry for such an enormous delay. We've just recently got our hands on and fixed the issue.
