### ISSUE TITLE
[windows] Is it supported?

### ISSUE THREAD

**Issue by ghost** [vkurenkov/haxball-chameleon#4]
why only linux? can't you support windows version?

**Comment by gamingmastar** [comment]
i tried on this script on windows its worked, you need to install anaconda, then install pytorch for working this, but after new haxball update came, not working anymore, this modified game js file need to be updated!

**Comment by vkurenkov** [comment]
@akelaa, we did not test it on windows, so we decided to go safe about it.

@gamingmastar, if you could provide a manual, it would be of immense help -- all contributions are welcome.
